### ISSUE TITLE
News Page

### ISSUE THREAD

**Issue by chrisopedia** [chrisopedia/mxpx.com#1]
* [ ] Copy over news from current site. This should be all the way back to release of Both Ends Burning & Plans Within Plans, so around 2012.

**Comment by chrisopedia** [comment]
@cnbartch this is something that will take a while to do, so we should prioritize this as pretty low, given that we can launch the site and still add old content as we go.  Thoughts?

**Comment by cnbartch** [comment]
Agreed.
If we start out with just the newest news item (the one which I posted last Friday about the live video and perks) and anything else that gets done between now and launch, that will work.

**Comment by cnbartch** [comment]
I am going to add the latest news item. Will give me the familiarity with the "blog post" editing.

**Comment by chrisopedia** [comment]
Oops, I already did.
