### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by chrisopedia** [chrisopedia/mxpx.com#13]
* What other front page content should we have? Featured video? A small widget that lists the closest upcoming tour dates? Obviously we don't want it too cluttered, but still want the most pertinent info easily available.
* Also - is it possible with this template to have the social icons show directly under the logo and Left Coast Punk site header? I think that would be preferable to them being at the bottom of the page.
* Only include the most current pieces on up to 3 items

**Comment by cnbartch** [comment]
Updated home page with section for featured content.
Will continue to tweak with Mike's suggestions.
Closed for now.
