### ISSUE TITLE
General Site Tasks

### ISSUE THREAD

**Issue by chrisopedia** [chrisopedia/mxpx.com#15]
* [ ] choose page backgrounds
* [x] get hi-res favicon

**Comment by cnbartch** [comment]
Put high res punk head graphic in Dropbox

**Comment by cnbartch** [comment]
For backgrounds - I just added 4 more files to the Dropbox, under pics, Jered Scott, hi res - these are all good options I think, I'll play around with them tonight.

**Comment by cnbartch** [comment]
Do you like the look of the background doing the stacked photos kind of like it is now? Or do you think it would be better to have only one photo?

**Comment by chrisopedia** [comment]
I think it'd be better to have just 1 image, but maybe you can change that for each page.
