### ISSUE TITLE
Tour Page

### ISSUE THREAD

**Issue by chrisopedia** [chrisopedia/mxpx.com#16]
Integrate bandsintown widget into shows/tour calendar, if possible

* [SquareSpace News](http://blog.squarespace.com/blog/squarespace-x-bandsintown)
* [Bandsintown Manager](http://www.artists.bandsintown.com/bandsintownartists/2014/6/16/introducing-bandsintown-manager-our-free-mobile-app-for-artists)
* [How to Use Widget](https://orangecourse.com/kb/article/add-bandsintown-squarespace-website/)

**Comment by chrisopedia** [comment]
@cnbartch it's looking like the bandsintown widget has limited options and might be best suited for a blog post in the News section.

**Comment by cnbartch** [comment]
Yes, lets go ahead and leave it like it is for now. Its very visually appealing. We can launch that way and I'll look into the Bandsintown widget some more.
